# Generated by Django 4.0.1 on 2022-01-21 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0002_userprofile_id_number_userprofile_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('registration_number', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('bodywork_type', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_profile', to='administration.userprofile')),
            ],
        ),
    ]
